\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.Group.Sub
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.MonoidCategory
\import Algebra.Monoid.MonoidHom
\import Algebra.Pointed
\import Algebra.Pointed.PointedCategory
\import Algebra.Pointed.PointedHom
\import Category
\import Category.Functor
\import Category.Meta
\import Category.Subcat
\import Equiv
\import Function (IsInj, IsSurj)
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta
\import Set.SetCategory

-- | The category of groups.
\instance GroupCat : Cat Group
  | Hom => GroupHom
  | id _ => GroupHom.id
  | o => GroupHom.∘
  | id-left => idp
  | id-right => idp
  | o-assoc => idp
  | univalence => sip \lam f _ => exts (f.func-ide, \lam _ _ => f.func-*, \lam _ => f.func-inverse)
  \where {
    -- | The forgetful functor from groups to sets.
    \func ForgetSet : FaithfulFunctor GroupCat SetCat \cowith
      | F G => G
      | Func f => f
      | Func-id => idp
      | Func-o => idp
      | isFaithful => \lam p => ext p

    -- | A group homomorphism is an isomorphism in 'GroupCat' if and only if it is a set-theoretic bijection.
    \lemma Iso<->Inj+Surj {G H : Group} (f : GroupHom G H) : Iso {GroupCat} f <-> f.IsIsomorphism
      => (\lam p => SetIso->Inj+Surj (ForgetSet.Func-iso p),
          \lam p => \new Iso {
            | hinv => \new GroupHom {
              | func => inve p
              | func-ide => {?}
              | func-* {x y : H} => {?}
            }
            | hinv_f => exts \lam e => inv (inv_this_ap p e)
            | f_hinv => exts \lam e => inv (this_inv_ap p e)
          })
      \where \private {
        -- | Shows that @h = f (f^-1 h)@.
        \lemma this_inv_ap (p : f.IsIsomorphism) (h : H) : h = f (inve p h)
          => {?}

        -- | Shows that @g = f^-1 (f g)@.
        \lemma inv_this_ap (p : f.IsIsomorphism) (g : G) : g = inve p (f g)
          => {?}

        -- | The isomorphism in 'SetCat' corresponding to the group isomorphism.
        \func this_iso (p : f.IsIsomorphism) => Inj+Surj->SetIso f p.1 p.2

        -- | The inverse mapping.
        \func inve (p : f.IsIsomorphism) => Iso.hinv {this_iso p}

        -- | A helper lemma for 'SetIso->Equiv'.
        \lemma aux {A B : \Set} (f : Iso {SetCat} {A} {B}) {a : A} {b : B} (p : f.f a = b) : f.hinv b = a
          => {?}

        -- | A helper lemma for 'SetIso->Equiv'.
        \lemma aux' {A B : \Set} (f : Iso {SetCat} {A} {B}) {a : A} : a = f.hinv (f.f a)
          => {?}

        -- | A helper lemma for 'SetIso->Equiv'.
        \lemma aux'' {A B : \Set} (f : Iso {SetCat} {A} {B}) {b : B} : b = f.f (f.hinv b) => {?}

        -- | A set-theoretic isomorphism is a bijection.
        \lemma SetIso->Inj+Surj(f : Iso {SetCat}) : \Sigma (IsInj f.f) (IsSurj f.f) => {?}

        -- | A set-theoretic bijection is an isomorphism.
        \lemma Inj+Surj->SetIso {X Y : \Set} (f : X -> Y) (p : IsInj f) (q : IsSurj f) : Iso {SetCat} f => {?}

        -- | An equivalence is an isomorphism.
        \lemma Equiv->SetIso {X Y : \Set} {f : X -> Y} (eq : Equiv f) : Iso {SetCat} f \cowith
          | hinv => Equiv.ret {eq}
          | hinv_f => ext (Equiv.ret_f {eq})
          | f_hinv => ext (Equiv.f_ret {eq})

        -- | An isomorphism is an equivalence.
        \lemma SetIso->Equiv {X Y : \Set} {f : X -> Y} (p : Iso {SetCat} f) : Equiv f => \new QEquiv {
          | ret => Iso.hinv {p}
          | ret_f x => inv (aux' p {x})
          | f_sec y => inv (aux'' p {y})
        }
      }

    -- | A group homomorphism is an isomorphism if and only if it is surjective and has a trivial kernel.
    \lemma Iso<->TrivialKer+Surj {G H : Group} (f : GroupHom G H)
      : Iso {GroupCat} f <-> (\Sigma f.TrivialKernel (IsSurj f))
      => {?}
      \where \private {
        -- | A helper lemma that relates injectivity and surjectivity with trivial kernel and surjectivity.
        \func helper : (\Sigma (IsInj f) (IsSurj f)) <-> (\Sigma f.TrivialKernel (IsSurj f)) => {?}
      }

  }

-- | The canonical projection from a group to its quotient by a normal subgroup.
\func quotient-map {S : Group} {H : NormalSubGroup S} : GroupHom S H.quotient \cowith
  | func (s : S) => NormalSubGroup.quotient-proj-setwise s
  | func-ide => idp
  | func-* => idp

-- | The image of a group homomorphism as a group.
\instance ImageGroup (f : GroupHom) : Group
  | Monoid => ImageMonoid f
  | inverse a => (inverse a.1, TruncP.map a.2 \lam s => (inverse s.1, f.func-inverse *> pmap inverse s.2))
  | inverse-left => {?}
  | inverse-right => {?}

-- | The inclusion of the domain into the image group.
\func ImageGroupLeftHom (f : GroupHom) : GroupHom f.Dom (ImageGroup f) \cowith
  | MonoidHom => ImageMonoidLeftHom f

-- | The inclusion of the image group into the codomain.
\func ImageGroupRightHom (f : GroupHom) : GroupHom (ImageGroup f) f.Cod \cowith
  | MonoidHom => ImageMonoidRightHom f

-- | The image of a group homomorphism as a subgroup of the codomain.
\func ImageSubGroup (f : GroupHom) : SubGroup f.Cod \cowith
  | contains h => ∃ (g : f.Dom) (f g = h)
  | contains_ide => {?}
  | contains_* cont1 cont2 => {?}
  | contains_inverse cont1 => {?}

-- | The category of additive groups.
\instance AddGroupCat : Cat AddGroup
  | Hom G H => AddGroupHom G H
  | id _ => AddGroupHom.id
  | o g f => \new AddGroupHom {
    | func x => g (f x)
    | func-+ => pmap g func-+ *> func-+
  }
  | id-left => idp
  | id-right => idp
  | o-assoc => idp
  | univalence => sip \lam {X} {A} {B} p1 p2 => exts (p1.func-zro, \lam _ _ => p1.func-+, AddGroup.negative-equality A B p1.func-zro p1.func-+)
  \where {
    -- | The forgetful functor from additive groups to additive monoids.
    \func forgetToAddMonoid : Functor AddGroupCat AddMonoidCat \cowith
      | F A => A
      | Func f => f
      | Func-id => idp
      | Func-o => idp

    -- | The forgetful functor from additive groups to sets.
    \func forget : Functor AddGroupCat SetCat \cowith
      | F R => R
      | Func f => f
      | Func-id => idp
      | Func-o => idp
  }

-- | The category of abelian groups.
\instance AbGroupCat : Cat AbGroup
=> subCat \new Embedding {AbGroup} {AddGroup} {
  | f A => A
  | isEmb A B => \new Retraction {
    | sec => AbGroup.equals A B
    | f_sec => idpe
  }
} \where {
  -- | The forgetful functor from abelian groups to additive groups.
  \func forgetToAddGroup : Functor AbGroupCat AddGroupCat \cowith
    | F A => A
    | Func f => f
    | Func-id => idp
    | Func-o => idp

  -- | The forgetful functor from abelian groups to sets.
  \func forget : Functor AbGroupCat SetCat \cowith
    | F R => R
    | Func f => f
    | Func-id => idp
    | Func-o => idp
}

-- | The kernel of an additive group homomorphism as an additive group.
\instance KerAddGroup (f : AddGroupHom) : AddGroup
  | AddMonoid => KerAddMonoid f
  | negative a => (negative a.1, f.func-negative *> pmap negative a.2 *> AddGroup.negative_zro)
  | negative-left => {?}
  | negative-right => {?}

-- | The inclusion of the kernel into the domain.
\func KerGroupHom (f : AddGroupHom) : AddGroupHom (KerAddGroup f) f.Dom \cowith
  | AddMonoidHom => KerMonoidHom f

-- | The kernel of an additive group homomorphism between abelian groups as an abelian group.
\instance KerAbGroup {A : AbGroup} (f : AddGroupHom A) : AbGroup
  | AddGroup => KerAddGroup f
  | AbMonoid => KerAbMonoid f

-- | A homomorphism of additive groups is injective if and only if its kernel is trivial.
\lemma kernel=0<->inj {f : AddGroupHom} : IsInj f <-> (\Pi (x : Kernel f) -> x = 0)
  => {?}

-- | The image of an additive group homomorphism as an additive group.
\instance ImageAddGroup (f : AddGroupHom) : AddGroup
  | AddMonoid => ImageAddMonoid f
  | negative a => (negative a.1, TruncP.map a.2 \lam s => (negative s.1, f.func-negative *> pmap negative s.2))
  | negative-left => {?}
  | negative-right => {?}

-- | The inclusion of the domain into the image additive group.
\func ImageAddGroupLeftHom (f : AddGroupHom) : AddGroupHom f.Dom (ImageAddGroup f) \cowith
  | AddMonoidHom => ImageAddMonoidLeftHom f

-- | The inclusion of the image additive group into the codomain.
\func ImageAddGroupRightHom (f : AddGroupHom) : AddGroupHom (ImageAddGroup f) f.Cod \cowith
  | AddMonoidHom => ImageAddMonoidRightHom f

-- | The image of an additive group homomorphism between abelian groups as an abelian group.
\instance ImageAbGroup {A : AddGroup} {B : AbGroup} (f : AddGroupHom A B) : AbGroup
  | AddGroup => ImageAddGroup f
  | AbMonoid => ImageAbMonoid f

-- | Conjugation by an element as a group homomorphism.
\func conjugateHom {E : Group} (g : E) : GroupHom E E \cowith
  | func => conjugate g
  | func-ide => unfold conjugate $ rewrite (E.ide-right, E.inverse-right) idp
  | func-* {x y : E} =>
    \have aux {x y z w t e : E} : x * y * z * (w * t * e) = (x * y) * (z * w) * (t * e) => equation
    \in {?}
