\import Algebra.Group
\import Algebra.Group.Sub
\import Algebra.Monoid
\import Algebra.Pointed
\import Logic
\import Logic.Meta
\import Paths
\import Relation.Equivalence
\import Set

-- | A G-set is a set with an action of a group G.
\class GroupAction (G : Group) \extends BaseSet {
  -- | The action of an element of G on an element of the set.
  | \infixl 8 ** : G -> E -> E -- priority should be bigger than priority of "+" in LModule (=7)
  | **-assoc {m n : G} {e : E} : m ** (n ** e) = (m * n) ** e
  | id-action {e : E} : ide ** e = e

  -- | The stabilizer of a point s is the subgroup of elements that fix s.
  \func Stabilizer (s : E) : SubGroup G \cowith
    | contains m => m ** s = s
    | contains_* {m n : G} (p : m ** s = s) (q : n ** s = s)  => {?}

    | contains_ide => id-action

    | contains_inverse {m : G} (p : m ** s = s) => {?}

  -- | Every point e determines a G-set of its orbit, which is isomorphic to G/Stabilizer(e).
  \func choosePoint (e : E) => ActionBySubgroup (Stabilizer e)
}

-- | A transitive action is an action with only one orbit.
\class TransitiveGroupAction \extends GroupAction
  | isTransAction : \Pi (v v' : E) -> ∃ (g : G) (g ** v = v')

-- | The canonical action of a group on the set of cosets of its subgroup by left multiplication.
\func ActionBySubgroup {G : Group} (H : SubGroup G) : GroupAction G \cowith
  | E => H.Cosets
  | ** (g : G) (e : H.Cosets) : H.Cosets \with {
    | g, in~ a => in~ (g * a)
    | g, ~-equiv x y r => {?}
    }
  | **-assoc {m n : G} {e : H.Cosets} : m ** (n ** e) = (m * n) ** e => {?}
  | id-action {e : H.Cosets} : ide ** e = e => {?}
  \where \func trivialRelation (g x y : G) : g * x * (inverse x * y) = g * y => {?}


-- | The action of a group on the cosets of any subgroup is transitive.
\instance TransitiveActionBySubgroup {G : Group} (H : SubGroup G) : TransitiveGroupAction G
   | GroupAction => ActionBySubgroup H
   | isTransAction (v v' : H.Cosets) : ∃ (g : G) (g ActionBySubgroup.** v = v') => {?}
