\import Algebra.Group
\import Algebra.Group.Sub
\import Algebra.Monoid
\import Arith.Nat
\import Equiv
\import Function.Meta
\import Logic
\import Logic.Classical
\import Meta
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set.Fin
\import Set.Fin.Instances
\import Set.Fin.KFin
\import Set.Fin.Pigeonhole
\open Group
\open Monoid(LDiv)

-- | The general Lagrange's theorem: if H is a subgroup of a group G and there is a choice function for cosets,
-- then G is equivalent to the sigma-type of cosets and elements of H.
\lemma lagrange-gen (H : SubGroup) (c : Choice H.Cosets) : TruncP (QEquiv {H.S} {\Sigma H.Cosets H.IGroup})
  => {?}

-- | Lagrange's theorem: the order of a subgroup of a finite group divides the order of the group.
\func lagrange (H : FinSubGroup) : LDiv (finCard {H.IFinGroup}) (finCard {H.S}) \cowith
  | inv => finCard {Cosets-fin H H.S}
  | inv-right => {?}
  \where {
    -- | The set of cosets of a decidable subgroup of a finite group is finite.
    \lemma Cosets-fin (H : DecSubGroup) (_ : KFinSet H.S) : FinSet H.Cosets
      => {?}
  }
