\import Algebra.Group
\import Algebra.Group.Fin
\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.RingHom
\import Arith.Fin.Order
\import Arith.Nat
\import Arith.Nat.Sequence
\import Combinatorics.Factorial
\import Data.Array
\import Data.Fin
\import Data.Or
\import Equiv
\import Equiv.Sigma
\import Equiv.Univalence
\import Function
\import Function.Meta
\import Logic.Unique
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.Fin
\import Set.Fin.Instances
\import Set.Fin.Pigeonhole

\type Sym (n : Nat) => Equiv {Fin n} {Fin n}
  \where {
    -- | A coercion from `Equiv {Fin n} {Fin n}` to `Sym n`.
    \func fromEquiv {n : Nat} (e : Equiv {Fin n} {Fin n}) : Sym n => {?}

    -- | Permutations are equal if they are equal as functions.
    \lemma equals {n : Nat} {x y : Sym n} (p : \Pi (j : Fin n) -> x j = y j) : x = y => {?}

    -- | `reduce e` is a permutation of `Fin n` obtained from `e : Sym (suc n)` by removing `0` and `e 0`.
    \func reduce {n : Nat} (e : Sym (suc n)) : Sym n => {?}

    -- | `reduce idEquiv = idEquiv`.
    \lemma reduce_id {n : Nat} : reduce {n} idEquiv = idEquiv => {?}

    -- | `Support e i` means that `e` moves `i`.
    \func Support {n : Nat} (e : Sym n) (i : Fin n) : \Prop => {?}

    -- | The set of elements moved by `e`.
    \func SupportFin {n : Nat} (e : Sym n) : FinSet (\Sigma (i : Fin n) (Support e i)) => {?}

    -- | If `i` is in the support of `e`, then it is also in the support of the inverse of `e`.
    \lemma Support_inverse {n : Nat} {e : Sym n} {i : Fin n} (s : Support e i) : Support (symQEquiv e) i => {?}

    -- | If `i` is in the support of `e`, then `e.ret i` is also in the support of `e`.
    \lemma Support_ret {n : Nat} {e : Sym n} {i : Fin n} (s : Support e i) : Support e (e.ret i) => {?}

    -- | If `i` is not in the support of `e`, then `e i = i`.
    \lemma Support_Not {n : Nat} {e : Sym n} {i : Fin n} (s : Not (Support e i)) : e i = i => {?}
  }

-- | `Sym n` is a group under composition.
\instance SymmetricGroup (n : Nat) : Group (Sym n)
  | ide => {?}
  | * e1 e2 => {?}
  | ide-left => {?}
  | ide-right => {?}
  | *-assoc => {?}
  | inverse e => {?}
  | inverse-left => {?}
  | inverse-right => {?}
  \where {
    -- | The inversion on `Sym n` is an equivalence.
    \func inv-isEquiv {n : Nat} : QEquiv {Sym n} {Sym n} \cowith
      | f e => {?}
      | ret e => {?}
      | ret_f e => {?}
      | f_sec e => {?}
  }

\open Sym \hiding (equals)

-- | A permutation is a cycle if its support is not empty and all its elements can be reached from a single element by repeated application of the permutation.
\type isCycle {n : Nat} (e : Sym n) : \Prop
  => ∃ (i : Support e) (∀ (j : Support e) (∃ (k : Nat) (Monoid.pow e k i = j)))

-- | Permutations with disjoint supports commute.
\lemma independent_* {n : Nat} {e e' : Sym n} (p : \Pi {i : Fin n} -> Support e i -> Support e' i -> Empty) : e * e' = e' * e => {?}

-- | If `i` is in the support of `e'`, then it is also in the support of `e * e'`.
\lemma independent_Support-right {n : Nat} {e e' : Sym n} (p : \Pi {i : Fin n} -> Support e i -> Support e' i -> Empty) {i : Fin n} (s : Support e' i) : Support (e * e') i => {?}

-- | If `i` is in the support of `e`, then it is also in the support of `e * e'`.
\lemma independent_Support-left {n : Nat} {e e' : Sym n} (p : \Pi {i : Fin n} -> Support e i -> Support e' i -> Empty) {i : Fin n} (s : Support e i) : Support (e * e') i => {?}

-- | If `i` is in the support of `e * e'`, then it is in the support of `e` or in the support of `e'`.
\lemma independent_Support-conv {n : Nat} {e e' : Sym n} (p : \Pi {i : Fin n} -> Support e i -> Support e' i -> Empty) {i : Fin n} (s : Support (e * e') i) : Support e i || Support e' i => {?}

-- | If `i` is in the support of one of the permutations in `l`, then it is also in the support of the product of all permutations in `l`.
\lemma independent_Support_BigProd {n : Nat} {l : Array (Sym n)}
                                   (p : \Pi (i1 i2 : Fin l.len) {i : Fin n} -> Support (l i1) i -> Support (l i2) i -> i1 = i2)
                                   {i : Fin n} {j : Fin l.len} (s : Support (l j) i) : Support (Monoid.BigProd l) i => {?}
  \where
    -- | If `i` is in the support of the product of all permutations in `l`, then it is in the support of one of the permutations in `l`.
    \lemma conv {n : Nat} {l : Array (Sym n)}
                (p : \Pi (i1 i2 : Fin l.len) {i : Fin n} -> Support (l i1) i -> Support (l i2) i -> i1 = i2)
                {i : Fin n} (s : Support (Monoid.BigProd l) i) : ∃ (j : Fin l.len) (Support (l j) i) => {?}

-- | Construct a cycle from an array of elements.
\func cycle {n k : Nat} (l : Array (Fin n) k) (inj : IsInj l) : Sym n => {?}
  \where {
    -- | The function that defines the cycle.
    \func func {n k : Nat} (l : Array (Fin n) (suc k)) (j : Fin n) : Fin n => {?}

    -- | `func` is injective.
    \lemma func-inj {n k : Nat} {l : Array (Fin n) (suc k)} (inj : IsInj l) {i j : Fin n} (q : func l i = func l j) : i = j => {?}

    -- | `suc x mod suc k = suc x` if `x /= k`.
    \lemma mod_/= {k : Nat} {x : Fin (suc k)} (p : x /= {Nat} k) : suc x Nat.mod suc k = {Nat} suc x => {?}

    -- | `suc x mod suc k` is injective.
    \lemma suc-inj {k : Nat} {x y : Fin (suc k)} (p : suc x Nat.mod suc k = suc y Nat.mod suc k) : x = y => {?}

    -- | `cycle l inj (l i) = l (i + 1 mod k)`.
    \func step {n k : Nat} {l : Array (Fin n) k} (k>0 : k > 0) (inj : IsInj l) (i : Fin k) : cycle l inj (l i) = l (mod_Fin (suc i) k>0) => {?}

    -- | `cycle l inj ^ m (l 0) = l m`.
    \lemma steps {n k : Nat} {m : Fin (suc k)} {l : Array (Fin n) (suc k)} {inj : IsInj l}
      : Monoid.pow {SymmetricGroup n} (PigeonholeSet.isEquiv (func l) (func-inj inj)) m (l 0) = l m => {?}
  }

-- | Construct a transposition of two distinct elements.
\sfunc transposition {n : Nat} {a b : Fin n} (a/=b : a /= b) : Sym n => {?}
  \where {
    -- | `a` and `b` are mapped to different values.
    \protected \func inj {i j : Fin 2} (p : (a :: b :: nil) i = (a :: b :: nil) j) : i = j => {?}

    -- | `transposition a/=b a = b`.
    \lemma transposition-left : transposition a/=b a = b => {?}

    -- | `transposition a/=b b = a`.
    \lemma transposition-right : transposition a/=b b = a => {?}

    -- | `transposition a/=b i = i` if `i /= a` and `i /= b`.
    \lemma transposition_/= {i : Fin n} (i/=a : i /= a) (i/=b : i /= b) : transposition a/=b i = i => {?}

    -- | `transposition a/=b` is its own inverse.
    \lemma transposition-isInv {i : Fin n} : transposition a/=b (transposition a/=b i) = i => {?}
  }

-- | Construct a transposition of `a` and `suc a` in `Sym (suc n)`.
\func transposition1 {n : Nat} (a : Fin n) : Sym (suc n) => {?}
  \where {
    \open transposition

    -- | `transposition1 a a = suc a`.
    \lemma transposition1-left {n : Nat} {a : Fin n} : transposition1 a a = suc a => {?}

    -- | `transposition1 a (suc a) = a`.
    \lemma transposition1-right {n : Nat} {a : Fin n} : transposition1 a (suc a) = a => {?}

    -- | `transposition1 a i = i` if `i /= a` and `i /= suc a`.
    \lemma transposition1_/= {n : Nat} {a : Fin n} {i : Fin (suc n)} (i/=a : i /= a) (i/=b : i /= suc a) : transposition1 a i = i => {?}

    -- | `transposition1 a i = i` if `suc a < i`.
    \lemma transposition1_> {n : Nat} {a : Fin n} {i : Fin (suc n)} (p : (suc a : Nat) < i) : transposition1 a i = i => {?}

    -- | `transposition1 a i = i` if `i < a`.
    \lemma transposition1_< {n : Nat} {a : Fin n} {i : Fin (suc n)} (p : (i : Nat) < a) : transposition1 a i = i => {?}

    -- | `transposition1 a` is its own inverse.
    \lemma transposition1-isInv {n : Nat} {a : Fin n} {i : Fin (suc n)} : transposition1 a (transposition1 a i) = i => {?}
  }

-- | If `i` is in the support of `cycle l inj`, then it must be one of the elements in `l`.
\func Support_cycle {n k : Nat} {l : Array (Fin n) k} (inj : IsInj l) {i : Fin n} (s : Support (cycle l inj) i) : \Sigma (j : Fin k) (l j = i) => {?}

-- | Any element in `l` is in the support of `cycle l inj` if `l.len > 1`.
\lemma cycle_Support {n k : Nat} {l : Array (Fin n) k} (k>1 : k > 1) {inj : IsInj l} {j : Fin k} : Support (cycle l inj) (l j) => {?}

-- | `cycle l inj` is a cycle if `l.len > 1`.
\lemma cycle-isCycle {n k : Nat} {l : Array (Fin n) k} {inj : IsInj l} (k>1 : k > 1) : isCycle (cycle l inj) => {?}

-- | The equivalence between `Sym (suc n)` and `(Fin (suc n), Sym n)`.
--   This is used to show that `Sym n` has `fac n` elements and to decompose a permutation into transpositions.
\func symmetric-rec {n : Nat} : QEquiv {Sym (suc n)} {\Sigma (Fin (suc n)) (Sym n)} \cowith
  | f e => {?}
  | ret s => {?}
  | ret_f e => {?}
  | f_sec s => {?}

-- | The cycle permutation `(k 0 1 ... n-1)`.
\func cyclePerm {n : Nat} (k : Fin n) : QEquiv {Fin n} {Fin n} => {?}

-- | The symmetric group `Sym n` is finite and has `fac n` elements.
\instance SymFin (n : Nat) : FinSet (Sym n) (fac n)
  | finEq => {?}
  \where {
    -- | The equivalence between `Fin (fac n)` and `Sym n`.
    \func fin_equiv {n : Nat} : Equiv {Fin (fac n)} {Sym n} => {?}
  }

-- | The set of equivalences between two finite sets is also a finite set.
\instance EquivFin (A B : FinSet) : FinSet (Equiv {A} {B}) => {?}
  \where {
    -- | The number of equivalences between `Fin n` and `Fin m`.
    \sfunc equiv_fin {n m : Nat} : \Sigma (k : Nat) (Equiv {Equiv {Fin n} {Fin m}} {Fin k}) => {?}
  }

-- | `lift e` is a permutation of `Fin (suc n)` that fixes `0` and acts as `e` on `Fin n`.
\func lift {n : Nat} (e : Sym n) : Sym (suc n) => {?}
  \where
    -- | `aux e` is a permutation of `Fin (suc m)` that fixes `0` and acts as `e` on `Fin n`.
    \func aux {n m : Nat} (e : Equiv {Fin n} {Fin m}) : Equiv {Fin (suc n)} {Fin (suc m)} => {?}

-- | `lift ide = ide`.
\lemma lift_ide {n : Nat} : lift {n} ide = 1 => {?}

-- | `lift (cycle l inj) = cycle (map fsuc l) (inj ∘ unfsuc)`.
\lemma lift_cycle {n k : Nat} {l : Array (Fin n) k} {inj : IsInj l} : lift (cycle l inj) = cycle (map fsuc l) (\lam {i} {j} p => inj (unfsuc p)) => {?}

-- | `lift (transposition a/=b) = transposition (fsuc/= a/=b)`.
\lemma lift_transposition {n : Nat} {a b : Fin n} {a/=b : a /= b} : lift (transposition a/=b) = transposition (fsuc/= a/=b) => {?}

-- | `lift (transposition1 a) = transposition1 (suc a)`.
\lemma lift_transposition1 {n : Nat} {a : Fin n} : lift (transposition1 a) = transposition1 (suc a) => {?}

-- | `lift (e * e') = lift e * lift e'`.
\lemma lift_* {n : Nat} {e e' : Sym n} : lift (e * e') = lift e * lift e' => {?}

-- | `lift (BigProd l) = BigProd (map lift l)`.
\lemma lift_BigProd {n : Nat} {l : Array (Sym n)} : lift (Monoid.BigProd l) = Monoid.BigProd (map lift l) => {?}

-- | Decompose a permutation into a product of transpositions of the form `transposition1 a`.
\func transposition1-decomp {n : Nat} (e : Sym (suc n)) : \Sigma (l : Array (Fin n)) (e = BigProd (map transposition1 l)) => {?}
  \where {
    \open Monoid
    \open NatOrder

    -- | If all permutations in `l` fix `i`, then their product also fixes `i`.
    \lemma BigProd-fixed {n : Nat} {l : Array (Sym n)} {i : Fin n} (p : ∀ (e : l) (e i = i)) : BigProd l i = i => {?}

    -- | If only one permutation in `l` moves `x`, then the product of all permutations in `l` maps `x` to the same value as that one permutation.
    \lemma BigProd-unique {n : Nat} {l : Array (Sym n)} {x : Fin n} (i : Fin l.len)
                          (p : \Pi (j : Fin l.len) -> (j : Nat) < i -> l j x = x)
                          (q : \Pi (j : Fin l.len) -> (i : Nat) < j -> l j (l i x) = l i x)
      : BigProd l x = l i x => {?}

    -- | A lemma used to decompose a permutation into transpositions.
    \lemma aux {n : Nat} (n>0 : n > 0) {e : Sym (suc n)} : e = lift (reduce e) * BigProd (\new Array (Sym (suc n)) (e 0) (\lam j => transposition1 (mod_Fin j n>0))) => {?}

    -- | A lemma used to show that the product of transpositions maps `0` to `k`.
    \lemma aux1 {n : Nat} (n>0 : n > 0) {k : Fin (suc n)} (e : Sym (suc n)) : BigProd (\new Array (Sym (suc n)) k (\lam j => transposition1 (mod_Fin j n>0))) 0 = k => {?}
  }

-- | The sign of a permutation.
\func sign {R : Ring} {n : Nat} (e : Sym n) : R => {?}
  \where {
    -- | The number of inversions of a permutation.
    \func inversions {n : Nat} (e : Sym n) : Nat => {?}

    -- | `inversions idEquiv = 0`.
    \lemma inversions_ide {n : Nat} : inversions {n} idEquiv = 0 => {?}

    \open NatOrder

    -- | The type of inversions of a permutation.
    \func Inversions {n : Nat} (e : Sym n) => \Sigma (i j : Fin n) (i < j) (e j < e i)

    -- | The set of inversions is finite and its cardinality is `inversions e`.
    \func InversionsFin {n : Nat} (e : Sym n) : FinSet (Inversions e) (inversions e) \cowith
      | finEq => {?}
      \where
        -- | The equivalence between `Fin (inversions e)` and `Inversions e`.
        \func aux {n : Nat} (e : Sym n) : Equiv {Fin (inversions e)} {Inversions e} => {?}

    -- | `f (sign e) = sign e` for any ring homomorphism `f`.
    \lemma sign_hom (f : RingHom) {n : Nat} {e : Sym n} : f (sign e) = sign e => {?}
  }

-- | `sign ide = 1`.
\lemma sign_ide {R : Ring} {n : Nat} : sign {R} {n} ide = ide => {?}

-- | `sign (e * e') = sign e * sign e'`.
\lemma sign_* {R : Ring} {n : Nat} {e e' : Sym n} : sign (e * e') = sign e R.* sign e' => {?}
  \where {
    \open sign
    \open transposition1
    \open NatSemiring (<-irreflexive)

    -- | A lemma used to show that `sign (transposition1 a * e) = -sign e`.
    \sfunc Inverstions_transposition_> {n : Nat} {e : Sym (suc n)} {a : Fin n} (ea<ea+1 : e a < e (suc a))
      : Equiv {Or (Inversions e) (Fin 1)} {Inversions (transposition1 a * e)} => {?}

    -- | A lemma used to show that `sign (transposition1 a * e) = -sign e`.
    \sfunc Inverstions_transposition_< {n : Nat} {e : Sym (suc n)} {a : Fin n} (ea+1<ea : e (suc a) < e a)
      : Equiv {Or (Inversions (transposition1 a * e)) (Fin 1)} {Inversions e} => {?}

    -- | `inversions (transposition1 a * e) = suc (inversions e)` if `e a < e (suc a)`.
    \lemma inverstions_transposition_> {n : Nat} {e : Sym (suc n)} {a : Fin n} (ea<ea+1 : e a < e (suc a))
      : suc (inversions e) = inversions (transposition1 a * e) => {?}

    -- | `inversions e = suc (inversions (transposition1 a * e))` if `e (suc a) < e a`.
    \lemma inverstions_transposition_< {n : Nat} {e : Sym (suc n)} {a : Fin n} (ea+1<ea : e (suc a) < e a)
      : suc (inversions (transposition1 a * e)) = inversions e => {?}

    \open Nat(mod)

    -- | `inversions (transposition1 a * e) mod 2 = suc (inversions e) mod 2`.
    \lemma inversions_transposition {n : Nat} {e : Sym (suc n)} {a : Fin n} : inversions (transposition1 a * e) mod 2 = suc (inversions e) mod 2 => {?}

    -- | `inversions (e * e') mod 2 = (inversions e + inversions e') mod 2`.
    \lemma inversions_* {n : Nat} {e e' : Sym n} : inversions (e * e') mod 2 = (inversions e + inversions e') mod 2 => {?}
      \where {
        -- | A helper lemma for `inversions_*`.
        \lemma aux {n : Nat} {l : Array (Fin n)} {e : Sym (suc n)} : inversions (Monoid.BigProd (map transposition1 l) * e) mod 2 = (inversions (Monoid.BigProd (map transposition1 l)) + inversions e) mod 2 => {?}
      }
  }

-- | `sign (inverse e) = sign e`.
\lemma sign_inverse {R : Ring} {n : Nat} {e : Sym n} : sign (inverse e) = {R} sign e => {?}

-- | `sign` is a monoid homomorphism.
\func signHom {R : Ring} {n : Nat} : MonoidHom (SymmetricGroup n) R \cowith
  | func => {?}
  | func-ide => {?}
  | func-* => {?}

-- | Decompose a permutation into a product of disjoint cycles.
\sfunc cycle-decomp {n : Nat} (e : Sym n) => {?}
  \where {
    \open Monoid(pow,BigProd)

    -- | Helper function for `cycle-decomp`.
    \func aux {k n : Nat} (e : Sym n) (p : finCard {Sym.SupportFin e} < k)
      : \Sigma (l : Array (Sym n))
               (∀ (e' : l) (isCycle e'))
               (\Pi (i1 i2 : Fin l.len) {i : Fin n} -> Support (l i1) i -> Support (l i2) i -> i1 = i2)
               (e = BigProd l) => {?}

    -- | If `pow e n x = pow e k x`, then `pow e (k - n) x = x`.
    \lemma pow-lem {N M : Nat} {n k : Fin M} {e : Sym N} {x : Fin N} (n<k : n < k) (p : pow e n x = pow e k x) : pow e (k -' n) x = x => {?}

    -- | `pow e (k mod m) i = pow e k i` if `pow e m i = i`.
    \lemma pow_mod {n k m : Nat} {e : Sym n} {i : Fin n} (p : pow e m i = i) : pow e (k Nat.mod m) i = pow e k i => {?}

    -- | `pow e k i = i` if `e i = i`.
    \lemma fixPoint-iter {n k : Nat} {e : Sym n} {i : Fin n} (p : e i = i) : pow e k i = i => {?}

    -- | `e (pow e k i) = pow e k (e i)`.
    \lemma pow-rotate {n : Nat} {e : Sym n} {k : Nat} {i : Fin n} : e (pow e k i) = pow e k (e i) => {?}
  }
