-- Defines `HasProduct` and `HasCoproduct` classes with operators `⨯` and `⨿`. Instances for `\Type` use `\Sigma` and `Or`.
-- Defines `HasProduct` and `HasCoproduct` classes with operators `⨯` and `⨿`, using `\Sigma` and `Or` for `\Type`.
-- Defines `HasProduct` and `HasCoproduct` classes for types with infix operators `⨯` and `⨿`, respectively. Instances for `\Type` use `\Sigma` and `Or`.
\import Data.Or

\class HasProduct (E : \hType)
  | Product \alias \infixl 7 ⨯ : E -> E -> E

\instance TypeHasProduct : HasProduct \Type
  | Product A B => \Sigma A B

\class HasCoproduct (E : \hType)
  | Coproduct \alias \infixl 6 ⨿ : E -> E -> E

\instance TypeHasCoproduct : HasCoproduct \Type
  | Coproduct => Or
