-- This file defines a `StrictPoset` class representing strict partial orders with irreflexivity and transitivity. It includes operations for reversing orders, lemmas for inequality reasoning, and checks if a function is strictly monotone between `StrictPoset` instances.
-- This file defines a `StrictPoset` class for strict partial orders, including properties like irreflexivity and transitivity. It also provides operations for reversing orders and lemmas for reasoning about strict inequalities. The function `IsStrictlyMonotone` checks if a function between two `StrictPoset` instances preserves strict order.
\import Logic
\import Paths
\import Set

-- | Strict partial orders are also known as quasiorders
\class StrictPoset \extends BaseSet {
  | \infix 4 < : E -> E -> \Prop
  | <-irreflexive {x : E} : Not (x < x)
  | <-transitive \alias \infixr 9 <∘ {x y z : E} : x < y -> y < z -> x < z

  | \infix 4 > : E -> E -> \Prop
  | > x y => y < x

  \protected \func op : StrictPoset E \cowith
    | < x y => y < x
    | <-irreflexive => <-irreflexive
    | <-transitive p q => q <∘ p

  \lemma <_/= {x y : E} (x<y : x < y) : x /= y
    => \lam x=y => <-irreflexive (transport (`< y) x=y x<y)

  \lemma >_/= {x y : E} (y<x : x > y) : x /= y
    => \lam x=y => <-irreflexive (transport (y <) x=y y<x)
} \where {
  \module Reasoning \where {
    \lemma \infixr 1 >>> {P : StrictPoset} {x y z : P} => P.<∘

    \lemma \infixr 1 >>= {P : StrictPoset} {x y z : P} (x<y : x < y) (y=z : y = z) => transport (x <) y=z x<y

    \lemma \infixr 1 >=> {P : StrictPoset} {x y z : P} (x=y : x = y) (y<z : y < z) => transport (`< z) (inv x=y) y<z

    \func \infix 2 <<< {P : StrictPoset} (x : P) {y : P} (p : x < y) => p
  }
}

\func IsStrictlyMonotone {X Y : StrictPoset} (f : X -> Y)
  => \Pi {x x' : X} -> x < x' -> f x < f x'